language: php
php:
  - 5.4
  - 5.5

script: vendor/bin/codecept run --coverage-xml

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --prefer-source
  - resources/supervisor.sh
  - sudo supervisord -c resources/supervisord.conf

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
