language: php
php:
  - 5.5
  - 5.4
  - 5.3

script: phpunit -v --coverage-clover=coverage.clover

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover