language: php
php:
  - 5.4
  - 5.5

script: vendor/bin/codecept run unit --coverage --xml

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_log/coverage.xml
